name: Build Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Add this line to enable manual runs

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Ensure the entire repository is checked out

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Change this line to use Node.js version 16

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: npm run make

      - name: Package Electron app
        run: npm run package

      - name: Upload artifact
        uses: actions/upload-artifact@v3 # Updated to v3
        with:
          name: electron-app-${{ matrix.os }}
          path: ./artifacts # Replace with the actual path to the artifact

  collect-artifacts:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3 # Updated to v3
        with:
          name: electron-app-ubuntu-latest
          path: ./artifacts/ubuntu
      - name: Download artifacts
        uses: actions/download-artifact@v3 # Updated to v3
        with:
          name: electron-app-macos-latest
          path: ./artifacts/macos
      - name: Download artifacts
        uses: actions/download-artifact@v3 # Updated to v3
        with:
          name: electron-app-windows-latest
          path: ./artifacts/windows

      - name: Upload all artifacts
        uses: actions/upload-artifact@v3 # Updated to v3
        with:
          name: all-electron-apps
          path: ./artifacts